[package]
name = "holdem"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14"
rand = "0.9"
rayon = "1.11"
egui = "0.33"
eframe = { version = "0.33", features = ["default"]}

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

